# Generated by Django 5.2.3 on 2025-10-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='data_cricao',
            new_name='data_criacao',
        ),
    ]
